### PR TITLE
refactor run.py PEP8

### PR DESCRIPTION
**Pull request by ghost**
Correct block comment, visual alignment

### CODE REVIEW

**Comment by martinpoliak-goodai** [comment]
Hi Stephen,
thanks for the pull request. I noticed you wanted to improve the style a little bit, but your pull request is inconsistent with other files (e.g. task_generator.py). Moreover, since other files (including the original CommAI repo) use triple single quotes for comments, we don't intend to switch to triple double quotes.
Thanks for understanding,
Martin

**Comment by ghost** [comment]
@martin The use of C style use of ''' and the Python PEP8 """ for block quotes are not consistent within the run.py file itself, both are used. The visual intent correction was also for PEP8.  May I suggest you add PEP8 not used, and list your projects unique conventions used in place of.

I believe there may be a potential type error on line 131 as well, where a str is expected, requires further testing. My intent was to review all the project files, the initial PR was to see if there was interest. I'm currently testing iso's for zesty, and realise this my be too fine grained a review for your project.

I was hoping to contribute in Q/A and code reviews here, as at a glance it does not appear Round1 was linted. Would it be preferable for your workflow if I direct my efforts upstream?

**Comment by martinpoliak-goodai** [comment]
Stephen, I'm not sure we're related to zesty or what zesty really means (is it the Kubuntu distribution?) - am I missing something?
Thank you for your code review offer, we appreciate it. However, since the challenge has been already running for some time and we have not heard any complaints from the participants, it does not have a high priority. 
If however you intend to fix the style of the whole repo (preferably minor changes only, definitely without changing the semantics of the code), we can then discuss the pull request again.

**Comment by ghost** [comment]
Sorry Zesty is the release name for Ubuntu 17.04, including all subsets Ubuntu, Kubuntu, Xubuntu etc being released this week. 

I appreciate your consideration of the PR, however it wouldn't be productive to refactor the code for PEP8 compliance, or any other linted, structured standards for the code base, as you have indicated you are not wishing for compliance with standards over in house practices. 

There is no standard to meet, therefore no changes are necessary. 

I will still be participating here, just limited to bug reports.

From your upstream Contributing to CommAI-env, PR steps 4 and 5, Ensure the test suite passes.
Make sure your code lints. 

Seems like a more appropriate place to assist with, as Round1 doesn't use formal testing or linting. I think this will cause issues in future as the rounds progress and the environment and challenge complexity increase.

**Pull request closed without merging**
